version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123qweASD
      MYSQL_DATABASE: db_quiz
      MYSQL_USER: user_quiz
      MYSQL_PASSWORD: 242322qWaS
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123qweASD
    ports:
      - "8081:80"